"""Add streak fields to user

Revision ID: 265957398a41
Revises: a1ebd596ef21
Create Date: 2026-06-28 16:54:16.923865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265957398a41'
down_revision = 'a1ebd596ef21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('longest_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_entry_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_entry_date')
        batch_op.drop_column('longest_streak')
        batch_op.drop_column('current_streak')

    # ### end Alembic commands ###
