"""Add notes to mood entries

Revision ID: a1ebd596ef21
Revises: 
Create Date: 2026-06-26 17:02:45.195220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1ebd596ef21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journalentries', schema=None) as batch_op:
        batch_op.alter_column('userID',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('moodentries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('userID',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moodentries', schema=None) as batch_op:
        batch_op.alter_column('userID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('notes')

    with op.batch_alter_table('journalentries', schema=None) as batch_op:
        batch_op.alter_column('userID',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
